name:                mini-java
version:             0.1.0.0
github:              "githubuser/mini-java"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mini-java#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- ansi-terminal >= 1.0 && < 2
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - array
    - bytestring
    - mtl

executables:
  mini-java-exe:
    main:                Main.hs
    source-dirs:         app
    build-tools:
    - alex
    - happy
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mini-java
    - directory

tests:
  mini-java-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mini-java
    - HUnit
    - aeson
    - bytestring
    - hspec
    - hspec-discover
